# Generated by Django 5.2.1 on 2025-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
