# Generated by Django 5.2.3 on 2025-06-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_teammember_photo_teammember_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='image',
            new_name='photo',
        ),
    ]
