# Generated by Django 5.2.3 on 2025-06-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_image_teammember_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image',
        ),
    ]
