# Generated by Django 5.2.1 on 2025-06-15 01:26

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL (e.g., https://example.com/image.jpg)', max_length=500, null=True, validators=[django.core.validators.URLValidator(), products.models.validate_image_url]),
        ),
    ]
