# Generated by Django 5.2.1 on 2025-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug_product_stock_product_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('product_type', models.CharField(max_length=50)),
                ('servings', models.PositiveIntegerField()),
                ('flavor', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('design_description', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('delivery_option', models.CharField(max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
