# Generated by Django 5.2.1 on 2025-06-19 10:06

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL (e.g., https://example.com/image.jpg)', max_length=500, null=True, validators=[django.core.validators.URLValidator(), products.models.validate_image_url]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[products.models.validate_image_size]),
        ),
    ]
