# Generated by Django 5.2.3 on 2025-06-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_image_url_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
